// Code generated by goctl. DO NOT EDIT!
// Source: shorten.proto

//go:generate mockgen -destination ./shortener_mock.go -package shortener -source $GOFILE

package shortener

import (
	"context"

	"shorturl/rpc/shorten/shorten"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	ShortenReq  = shorten.ShortenReq
	ShortenResp = shorten.ShortenResp

	Shortener interface {
		Shorten(ctx context.Context, in *ShortenReq) (*ShortenResp, error)
	}

	defaultShortener struct {
		cli zrpc.Client
	}
)

func NewShortener(cli zrpc.Client) Shortener {
	return &defaultShortener{
		cli: cli,
	}
}

func (m *defaultShortener) Shorten(ctx context.Context, in *ShortenReq) (*ShortenResp, error) {
	client := shorten.NewShortenerClient(m.cli.Conn())
	return client.Shorten(ctx, in)
}
