// Code generated by goctl. DO NOT EDIT!
// Source: expand.proto

//go:generate mockgen -destination ./expander_mock.go -package expander -source $GOFILE

package expander

import (
	"context"

	"shorturl/rpc/expand/expand"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	ExpandReq  = expand.ExpandReq
	ExpandResp = expand.ExpandResp

	Expander interface {
		Expand(ctx context.Context, in *ExpandReq) (*ExpandResp, error)
	}

	defaultExpander struct {
		cli zrpc.Client
	}
)

func NewExpander(cli zrpc.Client) Expander {
	return &defaultExpander{
		cli: cli,
	}
}

func (m *defaultExpander) Expand(ctx context.Context, in *ExpandReq) (*ExpandResp, error) {
	client := expand.NewExpanderClient(m.cli.Conn())
	return client.Expand(ctx, in)
}
