// Code generated by goctl. DO NOT EDIT!
// Source: expand.proto

package main

import (
	"flag"
	"fmt"

	"shorturl/rpc/expand/expand"
	"shorturl/rpc/expand/internal/config"
	"shorturl/rpc/expand/internal/server"
	"shorturl/rpc/expand/internal/svc"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/expand.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	srv := server.NewExpanderServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		expand.RegisterExpanderServer(grpcServer, srv)
	})
	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
